### ISSUE TITLE
Azure Data Studio/Redgate SQL Search

### ISSUE THREAD

**Issue by aspnerd** [red-gate/foundry#11]
When attempting to install the Redgate SQL Search in Azure Data Studio both preview and public did not work. Here is the log and screenshot.

`9/27/2018 7:01:49 PM - Microsoft VSIX Installer
9/27/2018 7:01:49 PM - -------------------------------------------
9/27/2018 7:01:49 PM - vsixinstaller.exe version:
9/27/2018 7:01:49 PM - 15.8.3252
9/27/2018 7:01:49 PM - -------------------------------------------
9/27/2018 7:01:49 PM - Command line parameters:
9/27/2018 7:01:49 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Files\Downloads\Redgate Foundry - Sql Search Extension.vsix
9/27/2018 7:01:49 PM - -------------------------------------------
9/27/2018 7:01:49 PM - Microsoft VSIX Installer
9/27/2018 7:01:49 PM - -------------------------------------------
9/27/2018 7:02:11 PM - Initializing Install...
9/27/2018 7:02:13 PM - Extension Details...
9/27/2018 7:02:13 PM - 	Identifier         : sql-search
9/27/2018 7:02:13 PM - 	Name               : Redgate SQL Search
9/27/2018 7:02:13 PM - 	Author             : Redgate
9/27/2018 7:02:13 PM - 	Version            : 0.2.1
9/27/2018 7:02:13 PM - 	Description        : Search across multiple databases
9/27/2018 7:02:13 PM - 	Locale             : en-US
9/27/2018 7:02:13 PM - 	MoreInfoURL        : 
9/27/2018 7:02:13 PM - 	InstalledByMSI     : False
9/27/2018 7:02:13 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
9/27/2018 7:02:13 PM - 
9/27/2018 7:02:13 PM - 	SignatureState     : Unsigned
9/27/2018 7:02:13 PM - 	Supported Products : 
9/27/2018 7:02:13 PM - 		Microsoft.VisualStudio.Code
9/27/2018 7:02:13 PM - 			Version : 
9/27/2018 7:02:13 PM - 
9/27/2018 7:02:13 PM - 	References         : 
9/27/2018 7:02:13 PM - Signature Details...
9/27/2018 7:02:13 PM - 	Extension is not signed.
9/27/2018 7:02:13 PM - 
9/27/2018 7:02:13 PM - Searching for applicable products...
9/27/2018 7:02:13 PM - Found installed product - Microsoft Visual Studio Enterprise 2015
9/27/2018 7:02:13 PM - Found installed product - Microsoft Visual Studio Professional 2015
9/27/2018 7:02:13 PM - Found installed product - Microsoft Visual Studio Community 2015
9/27/2018 7:02:13 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
9/27/2018 7:02:13 PM - Found installed product - Global Location
9/27/2018 7:02:13 PM - Found installed product - ssms
9/27/2018 7:02:13 PM - Found installed product - ssms
9/27/2018 7:02:13 PM - Found installed product - Visual Studio Enterprise 2017
9/27/2018 7:02:13 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
`

![image](https://user-images.githubusercontent.com/17560259/46179178-10eb5880-c288-11e8-8996-549055dd8223.png)

**Comment by aspnerd** [comment]
It would be nice if this installed without command line execution like other extensions.
