### ISSUE TITLE
[SQL Search Error]^

### ISSUE THREAD

**Issue by ceedubvee** [red-gate/foundry#40]
ERROR: Exception while indexing master on cmp-misql-dv1.ef1f6b4c7f5f.database.windows.net: 
DETAILS: System.Data.SqlClient.SqlException (0x80131904): Login failed for user ''.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Redgate.SqlSearch.Indexing.SQLServer.SQLServerInterface..ctor(String connectionString) in /home/vsts/work/1/s/sqlops-sql-search/backend/src/Redgate.SqlSearch.Indexing/SQLServer/SQLServerInterface.cs:line 125
   at Redgate.SqlSearch.Indexing.SQLServer.SQLServerInterfaceFactory.Build() in /home/vsts/work/1/s/sqlops-sql-search/backend/src/Redgate.SqlSearch.Indexing/SQLServer/SQLServerInterfaceFactory.cs:line 16
   at Redgate.SqlSearch.Indexing.IndexerBase.Index() in /home/vsts/work/1/s/sqlops-sql-search/backend/src/Redgate.SqlSearch.Indexing/IndexerBase.cs:line 75
ClientConnectionId:c36f431c-a135-4867-97d0-098000071d3e
Error Number:18456,State:1,Class:14

This should already be handling my user ID.

**Comment by davidsp2** [comment]
I also received the same error. Is this maybe an issue with Azure DBs?
