### ISSUE TITLE
I can't install the redgate sql search extenion in SQL ops studio

### ISSUE THREAD

**Issue by kakins** [red-gate/foundry#6]
When I navigate to the Extensions area in SOS, I click Install.  It opens up a browser window to https://www.redgatefoundry.com/SQLSearch.  When I click download, it downloads a .vsix, which when I try to run I get a dialog with the following error:

![image](https://user-images.githubusercontent.com/14915247/39765704-1bd9945a-52a8-11e8-829c-f7e153048e37.png)

Here's the end of the install log:

5/8/2018 10:11:41 AM - Searching for applicable products...
5/8/2018 10:11:41 AM - Found installed product - Microsoft Visual Studio 2010 Ultimate
5/8/2018 10:11:41 AM - Found installed product - Microsoft Visual Studio Ultimate 2012
5/8/2018 10:11:41 AM - Found installed product - Microsoft Visual Studio Premium 2012 
5/8/2018 10:11:41 AM - Found installed product - Microsoft Visual Studio Professional 2012
5/8/2018 10:11:41 AM - Found installed product - Microsoft Visual Studio 2012 Shell (Integrated)
5/8/2018 10:11:41 AM - Found installed product - Microsoft Visual Studio Professional 2015
5/8/2018 10:11:41 AM - Found installed product - Microsoft Visual Studio Community 2015
5/8/2018 10:11:41 AM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
5/8/2018 10:11:41 AM - Found installed product - Global Location
5/8/2018 10:11:41 AM - Found installed product - ssms
5/8/2018 10:11:41 AM - Found installed product - ssms
5/8/2018 10:11:41 AM - Found installed product - Visual Studio Professional 2017
5/8/2018 10:11:41 AM - Found installed product - Visual Studio Professional 2017 Preview (2)
5/8/2018 10:11:41 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by kakins** [comment]
Sorry, I'm bad about reading directions :)

![image](https://user-images.githubusercontent.com/14915247/39766174-400d162a-52a9-11e8-83cb-bbbcd5f5995e.png)

I needed to select "Install from VSIX".
